hydra:
  run:
    dir: .

data:
  root_dir: /home/umutdundar/Desktop/repositories/utkface-multitask/utkface-multitask/dataset/processed_split
  img_size: 224

training:
  batch_size: 32
  num_epochs: 5
  lr: 1e-3
  temperature: 0.07
logging:
  wandb:
    project: utkface-multitask
    name: contrastive_temp007_5class
    offline: True
    log_model: null
    save_dir: /home/umutdundar/Desktop/repositories/utkface-multitask/logs
