hydra:
  run:
    dir: .

data:
  root_dir: /home/umutdundar/Desktop/repositories/utkface-multitask/utkface-multitask/dataset/processed_split
  img_size: 224


training:
  multitask: True
  batch_size: 128
  num_epochs: 10
  # checkpoint: utkface-multitask/src/models/contrastive_temp007_5class.ckpt
  checkpoint: null
  lr: 1e-3
logging:
  wandb:
    project: utkface-multitask
    name: delete
    offline: False
    log_model: null
    save_dir: /home/umutdundar/Desktop/repositories/utkface-multitask/logs
    group: 6-classes
